name = "converter-worker"
main = "worker.js"
compatibility_date = "2025-12-21"

[build.upload]
format = "modules"

[worker]
external_modules = ["pdf-lib", "pdfjs-dist/legacy/build/pdf.js", "mammoth", "jszip"]
